# Generated by Django 6.0.6 on 2026-06-05 18:59

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='category/', verbose_name='Логотип категории')),
                ('title', models.CharField(max_length=155, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/', verbose_name='Изображение людей')),
            ],
            options={
                'verbose_name': 'Изображение человек',
                'verbose_name_plural': 'Изображения людей',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=155, verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Описание товара')),
                ('image1', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('image2', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('image3', models.ImageField(upload_to='product/', verbose_name='Изображение товара')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='settings.category', verbose_name='Категория товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
